### ISSUE TITLE
OSCAL Repository readme still points to retired architecture diagram

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#704] opened 2020-06-25 18:19 UTC
# Describe the bug

The readme.md that displays at the front of the OSCAL repo at https://github.com/usnistgov/OSCAL points to an architecture diagram that is no longer there, so a broken image icon appears. The following copy also makes reference to the diagram.

> ![image](https://user-images.githubusercontent.com/1588228/85777902-09bcdd00-b6f0-11ea-9029-d88721f6eec6.png)

# Expected behavior (i.e. solution)

The link and descriptive language should be either removed, or repaired.

Additionally, it would be nice if the site link checker under CI/CD could detect the error here. (Of course, this page isn't really in the site, so maybe not.)

**Comment by iMichaela** [comment] 2020-06-30 12:48
This issue, reporting missing diagram : 

https://github.com/usnistgov/OSCAL/raw/master/docs/content/learnmore/architecture/oscal-components.png

is identical to issue #696 (already in progress). The diagram exists (but only in Visio format) [here](https://github.com/usnistgov/OSCAL/blob/master/src/assets/OSCAL_Layers_Diagram.vsdx ). The diagram appears to be up to date. 
Suggest closing one of the two issues even before the updated information is pushed.

**Comment by wendellpiez** [comment] 2020-06-30 14:10
@iMichaela actually the page used to have the horizontal-bubble diagram not the layer cake diagram. Switching it out for the layer cake diagram is certainly an option. (Of course as you say the issues could be combined, especially if that is the determination.) @david-waltermire-nist has the latest/greatest layer cake diagram in clean, web-ready SVG.

**Comment by iMichaela** [comment] 2020-06-30 17:14
@wendellpiez The missing image in your ticket is pointing to https://github.com/usnistgov/OSCAL/raw/master/docs/content/learnmore/architecture/oscal-components.png which is the same URL as the one on the other ticket (I checked it before posting). David probably changed it when he worked on the website last time and removed the old 'bubble' diagram. So, both issues point to the same problem that might have been already addressed by @david-waltermire-nist, (since he assigned himself to address #696 ), but not pushed yet. Not a big issue.

**Comment by david-waltermire-nist** [comment] 2020-07-02 15:17
As a duplicate of #696.

**Closed by david-waltermire-nist** 2020-07-02 15:17 UTC
Labels: bug, duplicate
