### ISSUE TITLE
Create XML and JSON code examples for all commonly used OSCAL catalog and profile features

### ISSUE THREAD

**Issue by akarmel** [usnistgov/OSCAL#139] opened 2018-04-12 19:10 UTC
# User Story:

As an OSCAL consumer, I have access to XML and JSON code examples for all commonly used OSCAL catalog and profile features.

## Goals:

- Create XML and JSON code examples (@anweiss @wendellpiez)
- Link code examples to pages.nist.gov/OSCAL (@kscarf1)
- Code examples are usable for regression testing against OSCAL schemas (None)

## Dependencies:

None.

## Acceptance Criteria

- Ensure clear, concise, simple XML and JSON code examples exist for features used in 800.53 catalog and baselines
- Code examples are linked to pages.nist.gov/OSCAL

**Comment by wendellpiez** [comment] 2018-04-25 21:34
A lower-overhead, lower-maintenance approach to this would be to maintain a canonical set of complete examples, include them in regression testing (to guard against obsolescence), and point into them from the documentation for code examples.

However, this doesn't necessarily meet the requirements for display / integration into the docs. Would like some clarification as to what those are.

**Comment by wendellpiez** [comment] 2018-05-02 21:39
As soon as SP800-53 data is cleared cf #143, that can be an input here.

**Comment by kscarf1** [comment] 2018-05-17 01:44
**5/17/2018 - Sprint 10 Progress Report**

Goal: Create XML and JSON code examples
Progress: I have written several synthetic XML catalog code examples and provided these to Dave and Wendell for feedback. I expect to complete the examples for the XML catalog and profile schemas during this sprint.
% Complete: 15%
Open Issues: None

**Comment by kscarf1** [comment] 2018-05-23 19:19
**5/24/2018 - Sprint 10 Progress Report**

Goal: Create XML and JSON code examples
Progress: I have not made much progress on the XML examples this week, but I am still hoping to complete the XML examples for the catalog and profile schemas before the sprint acceptance meeting.
% Complete: 20%
Open Issues: None

**Comment by wendellpiez** [comment] 2018-05-24 14:19
**5/24/2018 - Sprint 10 Progress Report**

Meanwhile I have been working on the metaschema tech, one goal of which (external to Issue #125) is integrating the tagged examples into the docs, to facilitate both correctness (including validation) and maintenance. There are actually three different approaches to maintenance (on the XML side) that we can discuss: inline escaped XML (what we now have); inline XML; and pointers to out-of-line XML. Depending on our choice we have different choices on the JSON side. We could do any or all.

**Comment by anweiss** [comment] 2018-08-09 19:08
**August 9 Status:** This is dependent on refinements to the metaschema to clean up JSON schema and documentation outputs per #186 and #202.

**Comment by iMichaela** [comment] 2018-08-23 19:49
## Status Meeting: 8/23/2018 ##
@anweiss  will take a lead in addressing it.

**Comment by iMichaela** [comment] 2018-08-30 20:00
## 8/30/2018 Status Meeting ##
@anweiss suggests we should focus more on the metaschema (new ticket to be created by @anweiss)  to automatically translate the examples from XML to JSON. @anweiss and @wendellpiez and @david-waltermire-nist will continue working on it.

**Comment by anweiss** [comment] 2018-09-27 18:27
## 09/27/2018 ##

Discussed metaschema nuances with @wendellpiez. Refactoring `oscalkit` to automatically generate its own types based on the metaschema. This will enable `oscalkit` to generate code examples per the requirements of this issue; in addition to the XSLT being crafted to do the same.

**Comment by david-waltermire-nist** [comment] 2020-03-27 03:48
@anweiss What is the status of this issue?

**Comment by anweiss** [comment] 2020-03-27 14:47
@david-waltermire-nist it's been quite a while since I looked at this issue. However, @smichelotti and his team might have some samples that may shareable.

**Comment by david-waltermire-nist** [comment] 2020-09-11 17:23
This is being addressed by #592 and #593. Closing.

**Closed by david-waltermire-nist** 2020-09-11 17:23 UTC
Labels: LoE: Medium, Scope: Content, User Story
