### ISSUE TITLE
Broken links in profiles

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#534] opened 2019-11-06 21:35 UTC
# Describe the bug

As observed by one of our workshop participants, at least one call to a control from a profile is broken. (I can report more on where it is.)

# Who is the bug affecting?

Anyone who tries to use one of the broken profiles.

# Expected behavior (i.e. solution)

No links in published profiles should be broken.

# Other Comments

This bug could be banished forever with a validation check (under CI/CD) that would detect broken references to controls from profiles. An old Schematron is in the repo and could be refitted to current models and tested (although note that profile resolution or at least its selection logic is a dependency for a comprehensive solution).

**Comment by wendellpiez** [comment] 2019-11-22 15:17
I spun off a small Schematron to perform simple link checking from calls on controls from profiles.

@brianrufgsa this is what I see when I apply it to the FedRAMP baselines:

![image](https://user-images.githubusercontent.com/1588228/69437297-0522e700-0d11-11ea-9938-9be03fca3ae3.png)

Indeed, when I look at the catalogs cited by FedRAMP HIGH and MODERATE, they do not have the `-fr` suffix. (It's just `ac-8`.)

I will make a PR with the Schematron in it and report back.

Meanwhile these can be repaired easily enough.

**Comment by brianrufgsa** [comment] 2019-11-22 15:25
@wendellpiez This is very helpful! 
It accounts for an error I noticed in the resolved profile catalogs recently, but haven't had a chance to track down. 

For what it's worth, the fedramp catalog has ac-8.fr (dot, not dash) under an empty ac-8, as a way of inserting it as a child control to AC-8. (If there is a more appropriate way to do this, please let me know.) 

The problem is there are dashes in the profiles instead of dots. (ac-8-fr should be ac-8.fr)
When the more robust alter/add syntax is available, I'll make this correction along with those changes and push the fix.

**Comment by david-waltermire-nist** [comment] 2019-12-05 15:49
This work is being done in PR #546. PR #516 contains a schema fix, which has been merged into master. PR #546 needs to be rebased against master to pickup these changes.

**Comment by david-waltermire-nist** [comment] 2019-12-12 15:27
PR #539 implements a link checker that needs to be implemented in the CI/CD pipeline.

**Closed** 2019-12-19 13:56 UTC
Labels: bug
