### ISSUE TITLE
POAM JSON Outline: Risk > Remediation or Response?

### ISSUE THREAD

**Issue by rachkim00** [usnistgov/OSCAL#1766] opened 2023-04-20 00:02 UTC
### Describe the bug

In the [POAM JSON Outline](https://pages.nist.gov/OSCAL/reference/latest/plan-of-action-and-milestones/json-outline/), under 'Risk', instead of 'Response', it uses the term 'Remediations.' This section is the only part where it mentions 'Remediations' and it is confusing for the users whether remediation is another data type or the same as the response referred in 'Risk-log' > 'Related-**response**'. 

[XML outline](https://pages.nist.gov/OSCAL/reference/latest/plan-of-action-and-milestones/xml-outline/) only uses terminology 'response'.  

Unless it was intended to have POAM JSON to have different taxonomy by having separate 'Remediation' and 'Response', I suggest to update the 'Remediation' with 'Response'.

![POAM_JSON_Outline1](https://user-images.githubusercontent.com/125593357/233224062-f9eb6671-a0fc-4e43-b3d8-128de1227393.png)

### Who is the bug affecting

CSPs creating/implementing OSCAL POAM process.

### What is affected by this bug

OSCAL Content, Metaschema, Modeling

### How do we replicate this issue

1. Go to OSCAL Outline > JSON
2. Find Risk Section and check Remediation
3. Go to OSCAL Outline > XML
4. Compare with JSON outline

### Expected behavior (i.e. solution)

Term remediation is updated with 'response' in JSON outline

**Comment by aj-stein-nist** [comment] 2023-04-20 01:19
Hi @rachkim00, thanks for submitting this bug report. This appears to be a potential duplicate of https://github.com/usnistgov/OSCAL/issues/1618. We will discuss in the team's weekly issue triage and backlog refinement and update with notes in a follow-on comment.

**Closed** 2023-04-20 18:29 UTC
Labels: bug, duplicate
