### ISSUE TITLE
Identifier is shown as optional in DocumentID JSON Schema - should be shown as mandatory

### ISSUE THREAD

**Issue by RS-Credentive** [usnistgov/OSCAL#1823] opened 2023-06-28 10:16 UTC
### Describe the bug

The oscal catalog schema page lists the Identifier element of the DocumentID object as optional, when the JSON Schema shows it as mandatory.

### Who is the bug affecting

Users referencing the online schema

### What is affected by this bug

Documentation

### How do we replicate this issue

![Screenshot 2023-06-28 at 6 13 47 AM](https://github.com/usnistgov/OSCAL/assets/122729488/4c34a8ac-9ac0-46b1-ac43-635956902511)

![Screenshot 2023-06-28 at 6 15 55 AM](https://github.com/usnistgov/OSCAL/assets/122729488/4e85e869-6ecc-4520-bd0c-ea5a5f6fdc2a)

### Expected behavior (i.e. solution)

The page should list the identifier as [1]

**Comment by aj-stein-nist** [comment] 2023-07-06 18:40
OK, this is working as intended, I am going to close this issue after I post this, but feel free to re-open. I am closing this with the rationale of "this works as intended, we do not see a bug here." 

[Metaschema](https://pages.nist.gov/metaschema/) helps build a modeling system such that we have a framework that aligns *idiomatic* XML and JSON data structures, even when they are very different and copying one verbatim into the other would lead to incorrect syntax. This is really going to be a quick primer on "why does Metaschema work this way" and why these fields are optional. It is to make arrays of JSON maps/objects possible syntactically and with the object's properties optional or causing very complex handling with only JSON schema.

Let's suppose we have a XML data structure like this, which is what you're talking about:

```xml
<catalog>
  <metadata>
    <document-id scheme="http://example.com/document-id">identifier value</document-id>
  </metadata>
</catalog>
```

XML idiomatically doesn't use arrays, you can but, in many cases like this part of our XML model here, you repeat the elements in a row to be processed by XPath in the XML idiomatic way.

 ```xml
<catalog>
  <metadata>
    <document-id scheme="http://example.com/document-id">identifier value</document-id>
    <document-id scheme="http://different.tld/document-id">identifier value2</document-id>
  </metadata>
</catalog>
```

So we need to support one or more `document-ids` with an array, or XML-to-JSON alignment gets really, really messy. Let's find a way to convert this into JSON naively to start.

```json
{
    "catalog": {
        "metadata": {
            "document-ids": [
                {
                    "scheme": "http://example.com/document-id",
                    "identifier value"
                },
                {
                    "scheme": "http://different.tld/document-id",
                    "identifier value2"
                },
            ]
        }
    }
}
```

☝️ this is invalid JSON, this won't work, and without our array in JSON you would have to otherwise account for how XML has attributes and elements. Those elements can have their own values themselves (for which JSON needs a key-value pair identifier and you cannot have implicit values in `{}` map). But with array, we get into issues. For this reason, the embedded element value in XML needs a key to be JSON friendly, [as the metadata model embedded in the catalog defines with this `json-value-key`](https://github.com/usnistgov/OSCAL/blob/v1.0.6/src/metaschema/oscal_metadata_metaschema.xml#L943) (this is Metaschema syntax and trivia but will be important to know for the next bit).

So we have to allow for the following variations, all of them, and that is the reason Metaschema has the cardinality set the way you report as a bug.

```json
{
    "catalog": {
        "metadata": {
            "document-ids": [
                {
                    "scheme": "http://example.com/document-id",
                    "identifier": "identifier value1"
                },
                {
                    "scheme": "http://different.tld/document-id",
                    "identifier": "identifier value2"
                },
            ]
        }
    }
}
```

```json
{
    "catalog": {
        "metadata": {
            "document-ids": [
                {
                    "scheme": "http://example.com/document-id",
                    "identifier": "identifier value1"
                }
            ]
        }
    }
}
```


```json
{
    "catalog": {
        "metadata": {
            "document-ids": [
                {
                    "scheme": "http://example.com/document-id",
                }
            ]
        }
    }
}
```

```json
{
    "catalog": {
        "metadata": {
            "document-ids": [
                {
                    "identifier": "identifier value1"
                }
            ]
        }
    }
}
```


```json
{
    "catalog": {
        "metadata": {
            "document-ids": [{}]
        }
    }
}
```


```json
{
    "catalog": {
        "metadata": {
            "document-ids": []
        }
    }
}
```


```json
{
    "catalog": {
        "metadata": {}
    }
}
```
This is design decision with how Metaschema and OSCAL have been implemented historically, and there is no intent at this time to change for the major 1.x branch. Feel free to reopen or discuss in [communication channels with our community](https://pages.nist.gov/OSCAL/contact/) to argue otherwise, but that would be a systematic and very significant change that is not within our immediate priorities.

**Closed** 2023-07-06 18:43 UTC
Labels: bug
