### ISSUE TITLE
Produce a metaschema for the SSP model

### ISSUE THREAD

**Issue by akarmel** [usnistgov/OSCAL#267] opened 2018-12-10 21:57 UTC
# User Story:

As an OSCAL tool developer, I have a well documented metaschema for the OSCAL Implementation model.

## Goals:

Integrate the meta enhancements into the implementation model metaschema.

## Acceptance Criteria

1) Meta enhancements are clearly documented and incorporated into the implementation model metaschema

**Comment by brianrufgsa** [comment] 2018-12-20 20:39
Draft metaschema model is 100% complete is under review with @wendellpiez and @brianrufgsa before moving on to @david-waltermire-nist for final review.
Continue to work in Sprint 17.

**Comment by brianrufgsa** [comment] 2019-01-31 20:54
1/31/2019 Nearly complete draft is under refinement by Wendell and Brian. Intend to have a final draft by the end of next week.

**Comment by wendellpiez** [comment] 2019-02-07 15:30
**Progress Feb 7 2019**

We have been working on separate tracks -- @brianrufgsa proceeding to produce a description of a complete SSP as a metaschema, while I have been working with extracting sample data and designing a model to describe this "core" or "kernel" data (representing the control summary tables in the SSP).

This means that as of today, we have two SSP metaschemas, one not yet complete, the other nominally complete but partial. Completing this task means integrating these two.

However, a dependency for validating the adequacy of any SSP metaschema is data to validate and test, and this remains an issue.

% complete on this issue: 60%

**Comment by brianrufgsa** [comment] 2019-02-07 17:42
2/7/2019 - A complete draft SSP metaschema now exists, but is only partially documented, and partially validated.

**Comment by anweiss** [comment] 2019-02-07 17:51
@brianrufgsa do you have this pushed up anywhere yet?

**Comment by brianrufgsa** [comment] 2019-02-07 18:05
@anweiss: We are working to validate it so we can publish it. My hope is to have something published by 2/15/2019.  I know we can get the metaschema and XSD (for XML) published, but I'm not clear on what we can publish for JSON by that date. I'll need @wendellpiez to chime in as to exactly what that looks like and whether a similar timing is realistic.

**Comment by david-waltermire-nist** [comment] 2019-02-07 20:37
2/7/2019 - @brianrufgsa and @wendellpiez will create a branch (and a [WIP] PR) with the draft metaschema for sharing with the team.

**Comment by wendellpiez** [comment] 2019-02-11 19:50
@brianrufgsa has made a branch, here: https://github.com/brianrufgsa/OSCAL/tree/SSP-Metaschema-WIP

He's still getting used to git, and the iron is very hot (many changes happening) so what you see here may not be the latest on his system.

**Comment by brianrufgsa** [comment] 2019-02-14 21:27
2019-02-14: SSP Metaschema is a complete and fully functional draft. It was used to generate an XSD file, which was then successfully used to craft an actually ssp sml file based on real-world data. 
Need to formulate pull-request.

A few metaschema challenges to consider adjusting:
- Add a date type
- Adjust boolean type to allow yes/no, 0/1, and Null in addition to true/false
- Eliminate @group-as from model, and just use it from the field/assembly definition. Right now, they both have to match, which means they are redundant. When you use the same field in more than one model, this becomes a challenge.
- Instead of only allowing a field/assembly/flag to be defined once, allow them to be defined in context. For example, "title" appears in metaschema for the document title, and in "person" for a person's job title. The description and example for each is different. Currently, I need to include both descriptions and both examples in the one definition, or the description/example for the first instance also appears for the second instance.
- Prose needs expanded discussion. (Too much to include in this issue.)

**Comment by wendellpiez** [comment] 2019-02-25 16:30
We need a process for discussion of possible changes and enhancements to metaschema, including not only feature refinement / enhancement, but some sort of policy document  or rationale on how and why our design handles prose the way it does. (Which is by design, not accidental, but is not clearly articulated either.)

We might split this Issue into two: one for follow-on work testing the SSP/implementation schema and its design, and one to push back enhancements into the metaschema design.

**Comment by david-waltermire-nist** [comment] 2019-06-19 15:34
Closing this issue in favor of documenting new issues to define what needs to be done next.

**Closed by david-waltermire-nist** 2019-06-19 15:34 UTC
Labels: Scope: Formats, User Story
