### ISSUE TITLE
Missed Statement and Component Wrapping in Content Upgrades from M3 to RC to 1.0.0

### ISSUE THREAD

**Issue by ohsh6o** [usnistgov/OSCAL#959] opened 2021-06-10 01:19 UTC
# Describe the bug

During the course of work in GSA/fedramp-automation#106 to complete GSA/fedramp-automation#105, subsequent content upgrades of SSP content from `v1.0.0-milestone3` to `v1.0.0-rc1` to `v1.0.0-rc2` to `v1.0.0`, changes from M3 to 1.0.0-rc1 in content-upgrades, as evidence in upgrades from RC2 to 1.0.0 [did not pick up in the M3 to RC1 conversion, although it should have according to docs](https://github.com/usnistgov/OSCAL/blob/1f6154f0b02e67355629f8fd81f1acf97001f22c/docs/content/reference/release-notes.md) and [the transform itself](https://github.com/usnistgov/OSCAL/blob/f44426e0ec14431b88833dbd381b5434d0892403/src/release/content-upgrade/oscal-m3-rc1-elements.xsl#L438-L450).

This left upgraded example FedRAMP SSPs in an invalid state that fail XSD validation. 

This had to be [fixed manually or by transform with examples like this diff](https://github.com/GSA/fedramp-automation/pull/106/files#diff-f7f4fdd669b0c81a5db42ce3200f061cb8b4c8c3621906a68f6132b3ddab74d0R1096-R1112).

# Who is the bug affecting?

FedRAMP and other stakeholders maintaining example SSPs and OSCAL document instances, like SSP, and upgrading them programatically from version to version.

# What is affected by this bug?

All those using the content upgrade transforms.

# When does this occur?

Consistently for specific SSPs that did not construct `implemented-requirement`s with `statement`s with embedded `by-components` as it became mandatory from M3 to RC1.

# How do we replicate the issue?

{What are the steps to reproduce the behavior?
1. Do this...
1. Then this...
1. See error

```sh
/home/runner/work/fedramp-automation/fedramp-automation/git-content/src/templates/ssp/xml/FedRAMP-SSP-OSCAL-Template.xml:1195: element set-parameter: Schemas validity error : Element '{http://csrc.nist.gov/ns/oscal/1.0}set-parameter': This element is not expected. Expected is one of ( {http://csrc.nist.gov/ns/oscal/1.0}responsible-role, {http://csrc.nist.gov/ns/oscal/1.0}statement, {http://csrc.nist.gov/ns/oscal/1.0}by-component, {http://csrc.nist.gov/ns/oscal/1.0}remarks ).
```
Error message below from [past CI/CD job in Github Action](https://github.com/GSA/fedramp-automation/runs/2786697383?check_suite_focus=true).

# Expected behavior (i.e. solution)

The transform wrapped the `implemented-requirement`s `description`s correctly in `by-component` `statement`s.

**Comment by wendellpiez** [comment] 2021-06-11 13:35
@ohsh6o any chance of sharing an example showing the bug? Artificial is okay as long as it shows the bad output for the good inputs. (This could also give us a start on defining possible better behavior for inputs that are not actually good.)

I can help make an anonymizing filter for you if it is helpful to make shareable samples.

**Comment by ohsh6o** [comment] 2021-06-11 15:53
@wendellpiez, let me finish the baseline upgrade tasks and then I will work through a repro for you.

**Comment by ohsh6o** [comment] 2021-06-15 22:51
OK as asked, I deliver, @wendellpiez. I did the following:

1. Took a clone of [usnistgov/OSCAL at commit `0858d4f`](https://github.com/usnistgov/OSCAL/commit/0858d4ff7ddc60db113628eab75e161ddc1fff10).
2. Cloned a copy of [GSA/fedramp-automation at commit `6ba6ed3`, when existing sample template SSP and other artifacts were stll at `1.0.0-milestone3`](https://github.com/GSA/fedramp-automation/tree/6ba6ed399417f8bf00d31ed934912b2fc39b4228/src/baselines).
3. Ran [successive upgrade conversions version by version on the template SSP](https://github.com/GSA/fedramp-automation/blob/6ba6ed399417f8bf00d31ed934912b2fc39b4228/templates/ssp/xml/FedRAMP-SSP-OSCAL-Template.xml) with the following scripts from `0858d4f`:
 - `src/release/content-upgrade/oscal-m3-rc1-elements.xsl`
 - `src/release/content-upgrade/oscal-rc1-rc2-update.xsl`
 - `src/release/content-upgrade/oscal-rc2-v1-0-0-update.xsl`
4. Added the combined XSD header to the resulting file (`<?xml-model href="https://raw.githubusercontent.com/usnistgov/OSCAL/release-1.0/xml/schema/oscal_complete_schema.xsd" schematypens="http://www.w3.org/2001/XMLSchema" title="OSCAL complete schema"?>`)
5. Observe many validation errors where the `statement/by-component` assembly does not wrap, not all, but some are missing this as should be upgraded by the second script, per original report.

```xml
      <implemented-requirement control-id="ac-2" uuid="7a36cf53-156d-4d1f-9a8b-433f61cc57b7">
         <prop ns="https://fedramp.gov/ns/oscal"
               name="planned-completion-date"
               value="Completion Date"/>
         <prop name="implementation-status"
               ns="https://fedramp.gov/ns/oscal"
               value="planned">
            <remarks>
               <p>Describe the plan to complete the implementation.</p>
            </remarks>
         </prop>
         <prop name="implementation-status"
               ns="https://fedramp.gov/ns/oscal"
               value="partial">
            <remarks>
               <p>Describe the portion of the control that is not satisfied.</p>
            </remarks>
         </prop>
         <prop name="implementation-status"
               ns="https://fedramp.gov/ns/oscal"
               value="not-applicable">
            <remarks>
               <p>Describe the justification for marking this control Not Applicable.</p>
            </remarks>
         </prop>
         <prop name="control-origination"
               ns="https://fedramp.gov/ns/oscal"
               value="sp-system"/>
         <prop name="control-origination"
               ns="https://fedramp.gov/ns/oscal"
               value="customer-configured">
            <remarks>
               <p>Describe any customer-configured requirements for satisfying this control.</p>
            </remarks>
         </prop>
         <responsible-role role-id="admin-unix"/>
         <responsible-role role-id="program-director"/>
         <set-parameter param-id="ac-2_prm_1">
            <value>[SAMPLE]privileged, non-privileged</value>
         </set-parameter>
         <set-parameter param-id="ac-2_prm_2">
            <value>[SAMPLE]all</value>
         </set-parameter>
         <set-parameter param-id="ac-2_prm_3">
            <value>[SAMPLE]The Access Control Procedure</value>
         </set-parameter>
         <set-parameter param-id="ac-2_prm_4">
            <value>[SAMPLE]annually</value>
         </set-parameter>
         <statement statement-id="ac-2_stmt.a" uuid="24a85abb-25ad-4686-850c-5c0e8ab69a0c">
            <by-component component-uuid="3d035035-dfca-4240-9787-a7e8561e1c7d"
                          uuid="70bbeee7-f0ae-4502-839f-1db8a8ce9dd9">
               <description>
                  <p>Do not respond to this statement here. Respond within the <code>by-component</code> assembly below.</p>
               </description>
            </by-component>
            <by-component component-uuid="60f92bcf-f353-4236-9803-2a5d417555f4"
                          uuid="8a72663c-28c7-41c2-8739-f1ee2d5761ac">
               <description>
                  <p>For the portion of the control satisfied by this system or its owning organization, describe
                        <strong>how</strong> the control is met.</p>
               </description>
               <prop name="responsibility" value="customer">
                  <remarks>
                     <p>General customer responsibility description.</p>
                  </remarks>
               </prop>
               <remarks>
                  <p>The component-uuid above points to the "this system" component.</p>
                  <p>Any control response content that does not cleanly fit another system component is placed here. This includes customer responsibility content.</p>
                  <p>This can also be used to provide a summary, such as a holistic overview of how multiple components work together.</p>
                  <p>While the "this system" component is not expclicity required within every <code>statement</code>, it will typically be present.</p>
               </remarks>
            </by-component>
            <by-component component-uuid="b7364f67-bf65-4df2-b756-4b9c6b1c4a52"
                          uuid="84de735f-ba37-4bb4-b784-79760f986a40">
               <description>
                  <p>For the portion inherited from an underlying FedRAMP-authorized provider,
                     describe <strong>what</strong> is inherited.</p>
               </description>
               <prop name="responsibility" value="customer">
                  <remarks>
                     <p>Component-specific customer responsibility description.</p>
                  </remarks>
               </prop>
            </by-component>
            <by-component component-uuid="cae07d12-8566-443a-95de-7596b9cac953"
                          uuid="13db02bb-1f33-4f79-8711-ed47c2c3d337">
               <description>
                  <p>For the portion of the control that must be configured by or provided by the
                     customer, describe the customer responsibility here. This is what will appear
                     in the Customer Responsibility Matrix.</p>
               </description>
            </by-component>
         </statement>
      </implemented-requirement>
```

Attached each conversion step with [a Github Gist at this location](https://gist.github.com/ohsh6o/610165eb8d79a4f6dadb2ffbb3e8a52c). Please let me know about how I can help triage this or a misdiagnosed this bug. Thanks.
```

**Comment by wendellpiez** [comment] 2021-06-16 13:58
I examined the problem input and cannot validate it against any of the tagged schemas in the repository (for milestone3, rc1, rc2 or v1.0.0). Unfortunately this makes it out of scope since we can't easily model whatever "valid but exceptional" problem is underlying any transformation failures.

Suggest we close this ticket as a nothing-to-be-done (since the documents have all been upgraded in any case), unless we hear  word of other lapses.

**Comment by david-waltermire-nist** [comment] 2021-06-24 18:49
@ohsh6o The SSP template you provided is not valid to either Milestone 3 or RC1, which means testing the converter is not possible to find and fix this bug. If you can provide a Milestone 3 valid OSCAL example that illustrates this bug, we will gladly fix any bugs in the converter. Until we have a valid OSCAL example to reproduce this bug, we cannot do anything more.

I am going to close this issue for now. We can reopen it if you can provide a milestone 3 valid example that can be used to reproduce this bug.

**Closed by david-waltermire-nist** 2021-06-24 18:49 UTC
Labels: bug, wontfix
