### ISSUE TITLE
Explicit support for policies

### ISSUE THREAD

**Issue by degenaro** [usnistgov/OSCAL#989] opened 2021-07-09 11:07 UTC
# User Story:

As an OSCAL tool developer, I would like Component Definition to support `policies` as first class entities.

## Goals:

One way to describe the policy(s) associated with `implementation-requirements` is to employ property(s).  A suggested improvement is to enable explicit specification of policy.

For example, add optional `policies` as an array of `policy` objects under implementation-requirements.

## Dependencies:

N/A

## Acceptance Criteria

- [x] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [x] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire-nist** [comment] 2021-07-09 12:37
@degenaro We need more detail to understand this proposal.

1. What is a policy in this context?
2. What would the policy object contain?
3. What use case scenarios would this address that cannot be supported now?

 Can you explain more?

**Comment by degenaro** [comment] 2021-07-23 08:02
Working on this proposal, more coming soon.

**Comment by degenaro** [comment] 2021-08-05 12:31
Starting from the use case:
A single control is typically implemented by a set of technology-specific policies. E.g. "encryption at rest" would be implemented by policies to (i) encrypt block storage (ii) encrypt object storage (iii) setup MongoDB to use encryption etc. Each such policy needs to be validated in some way, lets say using a dedicated python function. Compliance tools need the standard to enable capturing these artifacts and the mappings between them.
Why this use case is currently not addressed:
Each object in the implemented-requirements array describes the implementation of a single control. The only mechanism to capture the mapping of multiple policies to this control is the props field, but we still need to capture the mapping of checks to policies. If each policy is specified as its own props object then we can only capture the name/description of the policy but not the mapping to the method(s) of checking it. Alternatively, if we use multiple props objects for each policy (with "name":"policy-id", "name":"policy-description", "name":"check-id", etc) then there is no native mechanism for grouping the props objects that describe the same policy.
Suggestion for extending the standard:
An implemented-requirements object should contain an array of policies, thus capturing the mapping between policies and controls. The props field of each policy can be used to capture the methods by which this particular policy is to be checked (could be a function name, pointer to a vendor tool feature, etc.).

**Comment by degenaro** [comment] 2021-08-05 12:42
1. _What is a policy in this context?_ Policy is one atomic check that tests a part of [fully] a control.
2. _What would the policy object contain?_ Props today contains a list of elements but not policy specific elements like Version, Parameters, Policy_Group(allowing to group props of the same policy).
3. _What use case scenarios would this address that cannot be supported now?_
Component Def or Assessment Plan must have the props abused to accommodate the policy specific elements, like concatenating the group.

Example of abuse, where `file_permissions_worker_service` is concatenated.

```
“props”: [ 
                 {
                   “ns” : ” http://ibm.github.io/compliance-trestle/schemas/oscal/cd/rhocp”
                   “name”: “goal_name_id”,
                   “value”: “file_permissions_worker_service”,
                   “class”: “scc_goal_name_id_file_permissions_worker_service”
                   “remarks” : “Ensure that the kubelet service file permissions are set to 644 or more restrictive”
                 },
                 {
                   “ns” : ” http://ibm.github.io/compliance-trestle/schemas/oscal/cd/rhocp”
                   “name”: “goal_version”,
                   “value”: “743d477 “,
                   “class”: “scc_goal_version_file_permissions_worker_service”
                   “remarks” : “file_permissions_worker_service”
                 } ,
 {
                   “ns” : ” http://ibm.github.io/compliance-trestle/schemas/oscal/cd/rhocp”
                   “name”: “goal_group_id”,
                   “value”: “743d477 “,
                   “class”: “scc_goal_id_file_permissions_worker_service”
                   “remarks” : “file_permissions_worker_service”
                 } …]

```

**Comment by david-waltermire-nist** [comment] 2021-08-20 14:23
@degenaro OSCAL SSPs allow components (of type `[policy](https://pages.nist.gov/OSCAL/reference/latest/system-security-plan/json-definitions/#/flag/oscal-implementation-common/system-component-type)`) to be used to represent a policy. A link on the component can be used to point to the actual policy document. Within `implemented-requirements` a `by-component` can be used to discuss the implementation details.

**Comment by ancatri** [comment] 2021-10-04 14:18
Related to https://github.com/usnistgov/OSCAL/issues/1032 where we need the policy / rule properly defined UUID to map the policy / rule defined in the comp def to the check implementation .

**Comment by david-waltermire-nist** [comment] 2022-03-04 21:08
Similar to #1032, we should hold off on addressing this until we make significant progress on #1058, since how we address rules may provide a different path for solving this. I am going to add this to the backlog for now.

**Comment by aj-stein-nist** [comment] 2023-09-26 19:47
This is already on the DEFINE board, just aligning the status given the status alignment discussed in our triage process on the wiki.

**Comment by iMichaela** [comment] 2023-12-12 03:17
> * _What is a policy in this context?_ Policy is one atomic check that tests a part of [fully] a control.
> * _What would the policy object contain?_ Props today contains a list of elements but not policy specific elements like Version, Parameters, Policy_Group(allowing to group props of the same policy).

This issue has good conversation which cannot converge since each person that provided a comment has a different understanding of what a 'policy' is and how should be used. Regulations are policies, 800-53 X-1 controls are policies. Bu the "atomic check" is a test assertion designed to assess the correct implementation of the control claiming to implement a policy requirements.

Even NIST defines 'policy' is slightly different ways:
A.
 = Statements, rules, or assertions that specify the correct or expected behavior of an entity. For example, an authorization policy might specify the correct access control rules for a software component.
Sources:
[NIST SP 1800-15B](https://doi.org/10.6028/NIST.SP.1800-15) from [NIST SP 800-95](https://doi.org/10.6028/NIST.SP.800-95), [NISTIR 7621 Rev. 1](https://doi.org/10.6028/NIST.IR.7621r1)
[NIST SP 1800-15C](https://doi.org/10.6028/NIST.SP.1800-15) from [NIST SP 800-95](https://doi.org/10.6028/NIST.SP.800-95), [NISTIR 7621 Rev. 1](https://doi.org/10.6028/NIST.IR.7621r1)
B.
  = A statement of objectives, rules, practices or regulations governing the activities of people within a certain context.
Sources:
[NISTIR 4734](https://doi.org/10.6028/NIST.IR.4734)

A password policy is not implemented by a system. The controls are implemented by the system and the controls need to meet the policy rules/objectives. 

Other OSCAL research work around rules (see #1058 ) aims to address this issue , if the 'policy support' requested is referring to test assertions per the clarification quoted above.

Closing this issue for now. If later we find that rules do not support this request we can reopen the issue.

**Closed by iMichaela** 2023-12-12 03:17 UTC
Labels: enhancement, User Story, Research, Aged
