### ISSUE TITLE
Move set-param elements to be inside their corresponding alter elements in profiles

### ISSUE THREAD

**Issue by anweiss** [usnistgov/OSCAL#292] opened 2019-01-17 19:29 UTC
# User Story:

As an OSCAL profile consumer, I need to be able to easily match the control/subcontrol `id` referenced by a `set-param` element with the `include`'d control in an `import`'ed profile/catalog. Current, `set-param` elements are group outside of an `alter`, and therefore relies on both a) an additional iteration ... and b) a correct `id` that matches an `include`'d `id. This is prone to error in that it makes iteration more complicated for tool vendors. More importantly, it makes it difficult to identify whether or not there are `id` errors and mismatches on the part of the profile maintainer, the catalog maintainer, or both.

Instead, if `set-param` elements are moved inside their corresponding `alter` elements, we have a guarantee that `set-param` is indeed referencing the intended control/subcontrol identified by the `alter` element.

## Goals:

Reduce errors when cross-referencing `set-param`'s to their corresponding control/subcontrol IDs and provide guarantees that the correct control/subcontrol is indeed being given the correct parameter. Give tool vendors an easier way to iterate through `set-param` elements.

## Dependencies:

None.

## Acceptance Criteria

OSCAL profile consumers can directly align `set-param` elements with their corresponding controls/subcontrols, thus reducing the risk for `id` cross-referencing errors. OSCAL tool vendors can more easily iterate through `set-param` elements.

**Comment by wendellpiez** [comment] 2019-01-31 14:55
(TL;DR: this requires further discussion. I do not agree that this would obviously be an improvement.)

Currently the binding of parameter settings to parameters -- and more importantly, parameters to their value insertion points in the flow of text -- is done by `@id`. This is the simplest way to do it and imposes no additional constraints beyond some lexical constraints plus document-scope uniqueness. It is true that under some processing models, this may introduce a need for two passes. (Other processing models  such as XSLT/XQuery's parse into a complete abstract model before transformation, can support this resolution in one pass b/c the model gives them effectively 'random access' to the document as a compiled, in-memory object. Thus XPath is designed to permit both forward and backward traversals imposing this problem for anyone implementing XPath.)

This rule would cater to (some) developers but it imposes new constraint in the model and makes validation more complex (such as needing a formal naming rule constraining parameter id values to relate them to their controls) -- while in general, arbitrary cross-referencing relations are not limited to parameters and their settings, so the problem might reappear in another guise. (As it has now again after I was induced to move 'references' in the catalog model for effectively the same reason.) Unless such cross-references -- wherever the document tree is made to imply or "declare" a graph by connecting to another node -- can be entirely excluded -- the issue for processing will remain.

Incidentally the same thing is true of parameters inside controls and subcontrols in catalogs - there is currently no rule that says they must be associated directly or by location or at all. For a couple of reasons we regard this is a feature not a bug. For example, being able to reuse a parameter value in more than one control -- SP800-53 doesn't do this, but it is not unreasonable to expect people to want to refactor parameters.

So the forms of cross-references we have include:

* parameters (declarations and settings) and their value insertion points inside controls
* citations to formal references
* arbitrary cross-references e.g. one control says "related to" another

**Comment by anweiss** [comment] 2019-01-31 17:30
@wendellpiez I think this is a pretty sound explanation. The gist seems to be that we're maximizing the flexibility of the profile model without imposing unnecessary constraints. So while this may add some complexity to artifact parsing, there are already a number of "tried and true" ways for accomplishing the task.

**Comment by wendellpiez** [comment] 2019-05-10 15:12
@anweiss puts this in a nutshell. This Issue can be reviewed and closed, I think.

**Comment by david-waltermire-nist** [comment] 2019-05-15 20:01
Ok. Closing.

**Closed by david-waltermire-nist** 2019-05-15 20:01 UTC
Labels: Scope: Formats, User Story, closable, wontfix
