### ISSUE TITLE
BUG: Wrong data set for link rel when "incorporated-into", for OSCAL Catalog

### ISSUE THREAD

**Issue by bsilberberg** [usnistgov/OSCAL#256] opened 2018-10-11 20:50 UTC
Found some bugs, when I was ingesting the data i found some oddities. 
[The Catalog](https://github.com/usnistgov/OSCAL/blob/master/content/nist.gov/SP800-53/rev4/NIST_SP-800-53_rev4_catalog.xml)
```
<subcontrol class="SP800-53-enhancement" id="cp-10.3">
            <title>Compensating Security Controls</title>
            <prop class="label">CP-10(3)</prop>
            <prop class="status">Withdrawn</prop>
            <link rel="incorporated-into" href="#Chapter 3">Chapter 3</link>
```
what is Chapter 3?

```
<control class="SP800-53" id="pl-5">
         <title>Privacy Impact Assessment</title>
         <prop class="label">PL-5</prop>
         <prop class="status">Withdrawn</prop>
         <link rel="incorporated-into" href="#Appendix J">Appendix J</link>
         <link rel="incorporated-into" href="#AR-2">AR-2</link>
      </control>
```
What is AR-2 or Appendix J?  I dont think these should be set there.

**Comment by iMichaela** [comment] 2018-10-12 19:59
@wendellpiez , @brianrufgsa and @david-waltermire-nist : It looks like the "withdrawn' bug we identified earlier and was supposed to be fixed in the current code is still here. Please note: CP-10(1) is withdrawn and not CP-10(3) as the snapshot above indicates. Also, Chapter 3 is not the one where the control is described. The control is described in Appendix F - see page F-73. However, the information above pertaining to PL-5 might not be properly represented with <link>. We need to discuss it asap (suggest Monday, 10/15/2018 via web) and fix the error.

![image](https://user-images.githubusercontent.com/13984545/46891308-6eaaa380-ce37-11e8-8ef1-df640c1ab653.png)

![image](https://user-images.githubusercontent.com/13984545/46891231-37d48d80-ce37-11e8-9018-a2f65a2550f6.png)

**Comment by brianrufgsa** [comment] 2018-10-13 01:02
I had called these to Wendell's attention a few months ago, as my ingest scripts also flagged these. When we discussed and explored them, we found they were more quirks in the actual document, rather than the data.

In the case of CP-10(3), it is a reference to Chapter 3 of the 800-53 r4 document itself; however, that content is not modeled in OSCAL, so the only href we could use is a pointer to the original PDF. To be candid, I'm not sure we reached a final decision on that. I believe we were waiting for Dave to return to escalate to him for a final decision; however, we had bigger fish to fry when Dave returned. 

In the case of PL-5, please note this is a withdrawn control in Rev 4. When you look at Table D-14, it says, "Incorporated into Appendix J, AR-2" 
This is intended to be a single reference as AR-2 is contained within Appendix J of 800-53 r4. Again, this content is not currently modeled in OSCAL, so the only legitimate href value is to point to the PDF; however, if we do that, we also need to combine the two link elements into a single link element.

**Comment by iMichaela** [comment] 2018-10-13 04:16
I would like to revisit these issues because CP-10(3) is **not** withdrawn as OSCAL version indicates -  only CP-10(1) is withdrawn.  So this is an error.

**Comment by wendellpiez** [comment] 2018-10-13 17:11
I am afraid we will need to go back to the NVD XML source data to confirm that the issues are not upstream of the extraction pipeline. There are already a few issues in the NVD sources which are provided for by patching in the mapping logic. We can do the same for any other problems we find. Errors like this can be due either to incorrect logic in the extraction, or incorrect/incomplete source data, or both - which is why they can be difficult to diagnose. Thanks for your attention to these issues.

Indeed, I can confirm that the NVD source data shows CP-10 (3) as withdrawn, as you'll find searching for that string here:

https://nvd.nist.gov/static/feeds/xml/sp80053/rev4/800-53-controls.xml

It is also not unusual for mapping exercises like this to discover discrepancies in the source data.

**Comment by david-waltermire-nist** [comment] 2018-10-25 19:53
@iMichaela Checked https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-53r4.pdf.

CP10(3) is actually withdrawn. No changes to make here.

The reference to "Incorporated into Appendix J, AR-2" and similar references need to be corrected in the OSCAL content to point to an external document reference to SP 800-53 rev4. We still need to do this.
Assigning @wendellpiez to make these changes to the document generation pipeline. @iMichaela and @brianrufgsa will provide any needed SP 800-53 subject matter expertise.

**Comment by david-waltermire-nist** [comment] 2018-11-01 19:39
11/1/2018 Status
---
We need to update the catalog to change the "Incorporated into Appendix J, AR-2" into a document reference to SP 800-53r4. We may also want to consider adding the Appendix J Privacy controls to the OSCAL catalog. @david-waltermire-nist will create a new issue for this.

**Comment by wendellpiez** [comment] 2018-11-02 22:20
Meeting Nov 2 @david-waltermire-nist and I ran out of time before defining the exact specification for this patch. (What should be the link text, and what exactly is the target of the link? Or should I provide my best answer?) Given a spec, I can implement it - if it can be done quickly, the emendation can be made with PR #261. Or this could await a "proper" handling when those target controls are available in OSCAL.

**Comment by iMichaela** [comment] 2018-11-08 20:49
## 11/08/2018 ##
@wendellpiez will provide an update this week.

**Comment by wendellpiez** [comment] 2018-11-08 21:17
@david-waltermire-nist and I refined our requirements for this last week (11/3) and I made the changes. PR #261 contains the revised file. Unfortunately it is too large for a git diff, so it will require downloading and using an offline diff tool to compare old and new (an XML diff tool is nice). Reviews by @brianrufgsa and @iMichaela would be especially welcome.

**Comment by wendellpiez** [comment] 2018-11-15 19:56
@brianrufgsa spot-checked the file and it looks okay to him (see #261).

**Comment by david-waltermire-nist** [comment] 2018-11-15 21:32
11/15/2018
---
Will close this.

before closing need to:
- Accept PR #261
- Create an issue for fixing the "appendix J" references as external document references.
- Create an issue for importing Appendix J controls in the OSCAL catalog.

**Comment by david-waltermire-nist** [comment] 2019-05-09 01:38
Created issues #346 and #347.

**Closed by david-waltermire-nist** 2019-05-09 01:38 UTC
Labels: Scope: Content, bug
