### ISSUE TITLE
Design Elements: Site URL

### ISSUE THREAD

**Issue by bbattaglini** [usnistgov/OSCAL#289] opened 2019-01-16 19:02 UTC
# User Story:

As an OSCAL website content owner, I want the OSCAL website URL to be easy to discover by the audience.

The URL should not be case sensitive. The solution may be to add an alias for the site.

The URL https://pages.nist.gov/OSCAL works, but the URL https://pages.nist.gov/oscal does not work.

## Goals:

Consolidate the website URL so the audience can easily find the project website.

## Dependencies:

None.

## Acceptance Criteria
Create an alias for the site so the variations of the URL (https://pages.nist.gov/OSCAL and https://pages.nist.gov/oscal) open the site.

Test and confirm https://pages.nist.gov/OSCAL opens the site.

Test and confirm https://pages.nist.gov/oscal opens the site.

**Comment by anweiss** [comment] 2019-01-16 19:24
Duplicate of https://github.com/usnistgov/OSCAL/issues/148

**Closed** 2019-01-25 14:01 UTC
Labels: User Story
